spring.application.name=config-server
server.port=8888

# Native profile for local configuration
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config

# Disable self-registration with Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
